version: '2'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - "5433:5432"
  app:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - "3099:3000"
    depends_on:
      - db
