default: &default
  adapter: <%= ENV["DB_ADAPTER"] || "postgresql" %>
  encoding: unicode
  host: <%= ENV["DB_HOST"] || "db" %>
  port: <%= ENV["DB_PORT"] || "5432" %>
  username: <%= ENV["DB_USERNAME"] || "postgres" %>
  password: <%= ENV["DB_PASSWORD"] || "password" %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
